language: csharp
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild
after_success:
  - mono ./testrunner/NUnit.Runners.2.6.4/nunit-console.exe UnitTestProject1/bin/Release/UnitTestProject1.dll
