language: csharp
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe UnitTestProject1/bin/Debug/UnitTestProject1.dll
